application: openidcx
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: build/html/index.html
  upload: build/html/index.html

- url: /(.*)
  static_files: build/html/\1
  upload: build/html/(.*)
